# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190227_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_emain', '修改邮箱')], max_length=20),
        ),
    ]
